#!/bin/bash
# Start the server (mainly for testing)

# TODO: Make a proper boot file.
erl -boot start_sasl -pa ebin/ -config app.config -eval '[ok=application:start(X) || X <- [inets, crypto, public_key, ssl, tricycle]].'
