#!/bin/bash
# Start the server (mainly for testing)

# TODO: Make a proper boot file.
erl -boot start_sasl -pa ebin/ -tricycle hudson_address '{"localhost",8080}' -eval 'application:start(inets), application:start(tricycle).'
